DROP TABLE IF EXISTS films, users, mpa_rating, film_genre, genre, likes, friends;

CREATE TABLE IF NOT EXISTS mpa_rating (
    mpa_id int PRIMARY KEY,
    name varchar(40)
);

CREATE TABLE IF NOT EXISTS genre (
    genre_id int PRIMARY KEY,
    name varchar(50)
);

CREATE TABLE IF NOT EXISTS films (
    film_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(70),
    description varchar(200),
    release_date date,
    duration int,
    mpa_id int REFERENCES mpa_rating (mpa_id)
    );



CREATE TABLE IF NOT EXISTS users (
    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(30),
    name varchar(40),
    email varchar(50),
    birthday date
    );


CREATE TABLE IF NOT EXISTS film_genre (
    film_id int REFERENCES films (film_id),
    genre_id int REFERENCES genre (genre_id)
    );


CREATE TABLE IF NOT EXISTS likes (
    film_id int REFERENCES films (film_id),
    user_id int REFERENCES users (user_id)
    );

CREATE TABLE IF NOT EXISTS friends (
    user_id int REFERENCES users (user_id),
    friend_id int REFERENCES users (user_id),
    friends_status int
    );